WITH CTE1
AS
(
	SELECT FULL_NAME, DAY_TYPE, [DATE], DATENAME(WEEKDAY, [DATE]) AS DayOfWeek
		  ,CONVERT(varchar, [DATE],112) - ROW_NUMBER() 
		   OVER (PARTITION BY FULL_NAME, DAY_TYPE ORDER BY [DATE]) AS PreviosDateForGroup
	   FROM [DATA]
	   WHERE DAY_TYPE = 'Sickness'
)
, CTE2
AS(
	SELECT FULL_NAME
		   ,CONVERT(DATE, MIN([DATE]), 23) AS SICKNESS_START 
		   ,CONVERT(DATE, Max([DATE]), 23) AS SICKNESS_END
		   , DATENAME(WEEKDAY, MIN([DATE])) AS SICKNESS_START_DAY
		   ,DATENAME(WEEKDAY, MAX([DATE])) AS SICKNESS_END_DAY
		FROM CTE1
		GROUP BY FULL_NAME, DAY_TYPE, PreviosDateForGroup
		ORDER BY 1 OFFSET 0 ROWS
),

--LEAD
--LAG
--1. DAY STATUS 

--ПОПЕРЕД ДЕНЬ ТИП
--СІКНЕС ПЕРІОД


--SELECT * FROM CTE2
--WHERE SICKNESS_START_DAY = 'Friday' OR SICKNESS_END_DAY='Monday'
--GROUP BY FULL_NAME,SICKNESS_START, SICKNESS_END, SICKNESS_START_DAY, SICKNESS_END_DAY


--SELECT 'RESULT'= CASE
--					WHEN SICKNESS_START_DAY = 'Friday' THEN 'F'
--					ELSE 'N'
--				 END
--	FROM CTE2
CTE3 
AS(
SELECT FULL_NAME, SICKNESS_START, SICKNESS_START_DAY, ROW_NUMBER() 
		   OVER (PARTITION BY FULL_NAME ORDER BY FULL_NAME) AS D
FROM CTE2 
WHERE SICKNESS_START_DAY IN ('Friday', 'Monday') AND SICKNESS_END_DAY IN ('Friday', 'Monday')
GROUP BY FULL_NAME, SICKNESS_START, SICKNESS_START_DAY)

SELECT * 
FROM CTE3

SELECT FULL_NAME
		   ,CONVERT(DATE, MIN([DATE]), 23) AS SICKNESS_START 
		   ,CONVERT(DATE, Max([DATE]), 23) AS SICKNESS_END
		   , DATENAME(WEEKDAY, MIN([DATE])) AS SICKNESS_START_DAY
		   ,DATENAME(WEEKDAY, MAX([DATE])) AS SICKNESS_END_DAY
		FROM CTE2
		GROUP BY FULL_NAME, DAY_TYPE, PreviosDateForGroup
		ORDER BY 1 OFFSET 0 ROWS


WITH CTE
AS(
SELECT FULL_NAME
	  ,DAY_TYPE
	  ,[DATE]
	  ,CAST(CONVERT(varchar, [DATE],112) AS INT) - CAST(LAG(CONVERT(varchar, [DATE],112), 1)  OVER (PARTITION BY FULL_NAME, DAY_TYPE ORDER BY [DATE]) AS INT ) AS LAGD
	  ,CAST(CONVERT(varchar, [DATE],112) AS INT) - CAST(LEAD(CONVERT(varchar, [DATE],112), 1)  OVER (PARTITION BY FULL_NAME, DAY_TYPE ORDER BY [DATE]) AS INT ) AS LEADD
	  ,CAST(LAG(CONVERT(varchar, [DATE],112), 1)  OVER (PARTITION BY FULL_NAME, DAY_TYPE ORDER BY [DATE]) AS INT ) - CAST(CONVERT(varchar, [DATE],112) AS INT)  AS LAGD1
	  ,CAST(LEAD(CONVERT(varchar, [DATE],112), 1)  OVER (PARTITION BY FULL_NAME, DAY_TYPE ORDER BY [DATE]) AS INT ) - CAST(CONVERT(varchar, [DATE],112) AS INT) AS LEADD1
	
	  --,LAG([DATE], 1)  OVER (PARTITION BY FULL_NAME, DAY_TYPE ORDER BY [DATE]) AS PrevDate
	  --,LEAD([DATE], 1) OVER (PARTITION BY FULL_NAME, DAY_TYPE ORDER BY [DATE]) AS NextDate
FROM [DATA]
WHERE DAY_TYPE = 'Sickness'
)

SELECT * FROM CTE

--SELECT FULL_NAME
--	  ,CONVERT(DATE, MIN([DATE]), 23) AS SICKNESS_START
--	  ,CONVERT(DATE, Max([DATE]), 23) AS SICKNESS_END
--FROM CTE
--GROUP BY FULL_NAME, DAY_TYPE, CC
--ORDER BY 1
	