USE [Learning]
GO

SELECT E.[FULL_NAME], E.[DEPARTMENT], E.[SALARY]
FROM EMPLOYEE16 AS E
JOIN	
	--count rows with the same salary within the same department
	(SELECT COUNT([SALARY]) AS CountRow
			,[DEPARTMENT]
			,[SALARY]
		FROM EMPLOYEE16
		GROUP BY [DEPARTMENT], [SALARY]) AS E1
ON E.DEPARTMENT=E1.DEPARTMENT AND E.SALARY=E1.SALARY
WHERE E1.CountRow>1
GO
