WITH CTE
AS
(
	SELECT FULL_NAME, DAY_TYPE, [DATE]
			,CONVERT(varchar, [DATE],112) - ROW_NUMBER() 
			OVER (PARTITION BY FULL_NAME, DAY_TYPE ORDER BY [DATE]) AS PreviosDateForGroup
		FROM [DATA]
			   
)
,CTE1
AS(
	SELECT FULL_NAME, DAY_TYPE
			,CONVERT(DATE, MIN([DATE]), 23) AS SICKNESS_START 
			,CONVERT(DATE, Max([DATE]), 23) AS SICKNESS_END
		FROM CTE
		GROUP BY FULL_NAME, DAY_TYPE, PreviosDateForGroup
		ORDER BY 1,3 OFFSET 0 ROWS
)
, CTE2
AS
(
	SELECT FULL_NAME, DAY_TYPE,LEAD(DAY_TYPE,1) OVER (ORDER BY FULL_NAME,SICKNESS_START) AS LEAD_DAY_TYPE,
	SICKNESS_START, 
	SICKNESS_END,
	LEAD(SICKNESS_END,1) OVER (ORDER BY FULL_NAME,SICKNESS_START) AS LEAD_SICKNESS_END
	FROM CTE1
	ORDER BY 1 OFFSET 0 ROWS
)
SELECT FULL_NAME, SICKNESS_START, SICKNESS_END FROM CTE2 WHERE DAY_TYPE='Sickness' AND LEAD_DAY_TYPE <> 'Sickness'
UNION ALL
SELECT FULL_NAME, SICKNESS_START, LEAD_SICKNESS_END FROM CTE2 WHERE DAY_TYPE = LEAD_DAY_TYPE 
ORDER BY 1,2